# For more details on how configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

# The name of your Worker.
name = "next-starter-template"

# The path to the entrypoint of your Worker.
main = ".open-next/worker.js"

# Compatibility date for the Workers runtime.
compatibility_date = "2025-04-01"

# Compatibility flags to enable additional features in the runtime.
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
assets = { binding = "ASSETS", directory = ".open-next/assets" }

# Observability settings for telemetry data.
observability = { enabled = true }

# When true, Wrangler uploads source maps on deploy.
upload_source_maps = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# Uncomment the following section to enable Smart Placement.
# [placement]
# mode = "smart"

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
# databases, object storage, AI inference, real-time communication, and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "WORKER_SELF_REFERENCE"
# service = "next-starter-template"

# D1 Database Bindings
# https://developers.cloudflare.com/d1/
[[d1_databases]]
binding = "DB"
database_name = "insulin-tracker"
database_id = "1e3b4d4a-0796-49a3-adc8-8063d6e0ffe0"

# KV Namespace Bindings
# https://developers.cloudflare.com/kv/
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "b2f870bf8bf54dbd882e46d52466f87c"
